// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2PFRc2VtUVov_cQZxxeE4S24PCpA3Swk',
    appId: '1:43972438277:web:94c775e35418da64a7ef6c',
    messagingSenderId: '43972438277',
    projectId: 'pingo-comment',
    authDomain: 'pingo-comment.firebaseapp.com',
    storageBucket: 'pingo-comment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4ap6DSXcgnwAoboPABB9ztOY3MDkAsb8',
    appId: '1:43972438277:android:40c85f06862a8e8da7ef6c',
    messagingSenderId: '43972438277',
    projectId: 'pingo-comment',
    storageBucket: 'pingo-comment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgD6ZY1oWnxyKIwgS5Yc8oTsh-yd_QgKo',
    appId: '1:43972438277:ios:608df920938894c7a7ef6c',
    messagingSenderId: '43972438277',
    projectId: 'pingo-comment',
    storageBucket: 'pingo-comment.appspot.com',
    iosBundleId: 'com.example.pingoComment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgD6ZY1oWnxyKIwgS5Yc8oTsh-yd_QgKo',
    appId: '1:43972438277:ios:608df920938894c7a7ef6c',
    messagingSenderId: '43972438277',
    projectId: 'pingo-comment',
    storageBucket: 'pingo-comment.appspot.com',
    iosBundleId: 'com.example.pingoComment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2PFRc2VtUVov_cQZxxeE4S24PCpA3Swk',
    appId: '1:43972438277:web:10fd64b85a6523d7a7ef6c',
    messagingSenderId: '43972438277',
    projectId: 'pingo-comment',
    authDomain: 'pingo-comment.firebaseapp.com',
    storageBucket: 'pingo-comment.appspot.com',
  );
}
